services:
  - type: web
    name: book-data-scraper
    env: python
    region: oregon  # or use frankfurt if you're in Europe
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
